# ===========================================
# TensorFlow_Projects Configurations
# ===========================================

global:
  seed: 42
  output_dir: "Results/"
  log_dir: "Results/logs/"

data:
  mnist:
    normalize: true
    flatten: true
  cifar10:
    normalize: true
  imdb:
    num_words: 10000
    maxlen: 200

train:
  batch_size: 64
  epochs: 10
  validation_split: 0.1
  learning_rate: 0.001
  early_stopping_patience: 3


models:
  dense_mnist:
    hidden_units: [512, 256]
    dropout_rates: [0.3, 0.2]
  cnn_cifar10:
    filters: [32, 64, 128]
    dense_units: 128
  rnn_imdb:
    embed_dim: 128
    lstm_units: 64
  transfer_mobilenetv2:
    base_trainable: false

logging:
  plots_dir: "results/plots/"
  tensorboard_dir: "results/logs/"
  save_figures: true